name: 'Microwalk Jalangi2'
description: 'Analyze JavaScript code with the Microwalk Jalangi2 backend'
inputs:
  analysis-script-directory:
    description: 'Directory path of the analyze.sh script'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.analysis-script-directory }}